import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../sass/main.scss";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { getGlobalSettings } from "@/data/loader";
import { notFound } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
async function loader() {
  const res = await getGlobalSettings(); // Axios: res.data, fetch: res
  const root = res?.data ?? res;                  
  const attrs = root?.data?.attributes ?? root?.data ?? root; // Strapi v4 shapes

  const header = attrs?.Header ?? attrs?.header;
  const footer = attrs?.Footer ?? attrs?.footer;

  if (!header || !footer) {
    console.log("Global settings payload:", JSON.stringify(res, null, 2));
    throw new Error(
      `Failed to fetch global settings (${
        !header ? "Header" : "Footer"
      } not found)`
    );
  }

  return { header, footer };
}



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {header, footer} = await loader();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header data={header}/>
        {children}
        <Footer data={footer}/>
      </body>
    </html>
  );
}
